= Netkit Docs

== Overview

This repo hosts the source code for https://netkit-jh.github.io which covers documentation on using and developing netkit-jh.

== Contributing

To contribute to the website please fork this repository and submit your changes as a pull request.

=== Blog Posts

To add a blog post create a markdown file in the `blog` directory with the naming convention *YYYY-MM-DD-BLOG-NAME.md*.

For information on formatting of blog posts, see the documentation link:https://v2.docusaurus.io/docs/blog[here].

=== Documentation

To add a page to the docs, create a markdown file in the `docs` directory (and in the relevant subdirectory if necessary). 
For guidance on markdown formatting see the documentation link:https://v2.docusaurus.io/docs/markdown-features[here].

== ToDo

* [ ] Make logo and favicon
* [ ] Create / find graphics for homepage
* [*] Installation Guide
* [ ] About netkit-jh page
* [ ] Testing guide (abr lab from scratch and walkthrough)
* [ ] Upcoming Features Page
* [ ] Building with docker guide
* [ ] Building with bullseye VM guide
* [ ] Page for each current bug
* [ ] add FAQ for common bugs / error messages
