name: build-site

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout git repo
      - uses: b177y/actions-yarn@master
        name: Install yarn packages
        with:
          cmd: install
      - uses: b177y/actions-yarn@master
        name: build and deploy site
        with:
          cmd: deploy
        env:
          GIT_USER: ${{ github.actor }}
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          USE_SSH: true
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
