name: build-site

on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: deploy
        env:
          GIT_USER: ${{ github.actor }}
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
