name: build-site

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout git repo
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          which ssh
          apt install openssh-client
      - uses: borales/actions-yarn@v2.0.2
        name: Install yarn packages
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.2
        name: build and deploy site
        with:
          cmd: deploy
        env:
          GIT_USER: ${{ github.actor }}
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          USE_SSH: true
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
